# Generated by Django 4.2.1 on 2023-06-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_coursemealcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemealcategory',
            options={'verbose_name_plural': 'Course Meal Categories'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'Food'},
        ),
    ]
