# Generated by Django 4.1.9 on 2023-06-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_alter_coursemealcategory_options_alter_food_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemealcategory',
            name='description',
            field=models.CharField(max_length=510),
        ),
    ]
